### PR TITLE
Feature/#browsernotification

### PR DESCRIPTION
**Pull request by oreyes1991**
This will make browser notifications if allowed when there is new visitor / registrant 
per channel.

### CODE REVIEW

**Comment by jegj** [comment]
Before merge this branch  rebase it with develop  for a small change

**Review by jegj — CHANGES_REQUESTED** [review]
update with develop

**Review by pablolimo — APPROVED** [review]

**Comment by jegj** [comment]
Update this branch with the develop(gain) to avoid problems with dependecies

**Comment by oreyes1991** [comment]
i added the redirect to the thread on click the notification, and list all visitors in operator's view

**Comment by oreyes1991** [comment]
also i have to set back the 
```
 "engines": {
    "node": "8"
  }
```
Firebase functions only support 6 or 8

**Review by jegj — APPROVED** [review]

**Review by jegj — APPROVED** [review]

**Review by pablolimo — APPROVED** [review]

**Pull request merged**
